language: node_js

matrix:
  include:
    - node_js: '14'
      env: MODE=jest
      dist: trusty

cache: yarn

script:
  - /bin/bash test.sh

after_success:
  - yarn add codecov
  - node node_modules/.bin/codecov


